/*
==============================================================================
==============================================================================
*/

$modelname "crate_small.mdl"
$cd ".\"
$cdtexture ".\"
$scale 1.0
$cliptotextures
$origin 0.000000 0.000000 0.000000
$flags 512

//reference mesh(es)
$bodygroup "studio"
{
studio "crate01_reference"
}

// 3 animation sequence(s)
$sequence "idle1" "idle1" fps 1
