/*
===============================================
Pathos Engine - Created by Andrew Stephen "Overfloater" Lucas

Copyright 2016
All Rights Reserved.
===============================================
*/

#ifndef ANIMEVENT_H
#define ANIMEVENT_H

enum animevent_t
{
	EVENT_SCRIPT_DEAD							= 1000,
	EVENT_SCRIPT_NOINTERRUPT					= 1001,
	EVENT_SCRIPT_CANINTERRUPT					= 1002,
	EVENT_SCRIPT_FIREEVENT						= 1003,
	EVENT_SCRIPT_SOUND							= 1004,
	EVENT_SCRIPT_SENTENCE						= 1005,
	EVENT_SCRIPT_INAIR							= 1006,
	EVENT_SCRIPT_ENDANIMATION					= 1007,
	EVENT_SCRIPT_SOUND_VOICE					= 1008,
	EVENT_SCRIPT_SENTENCE_RND					= 1009,
	EVENT_SCRIPT_NOT_DEAD						= 1010,

	EVENT_CLIENT_START_INDEX					= 5000,

	EVENT_CLIENTDLL_MUZZLEFLASH_SIMPLE_A1		= 5001,
	EVENT_CLIENTDLL_SPARK_A1					= 5002,
	EVENT_CLIENTDLL_PLAYSOUND_A1				= 5004,
	EVENT_CLIENTDLL_PLAYSOUND_A1_PLAYER			= 5005,
	EVENT_CLIENTDLL_PLAYSOUND_A1_CHAN_ITEM		= 5006,
	EVENT_CLIENTDLL_MUZZLEFLASH_SIMPLE_A2		= 5011,
	EVENT_CLIENTDLL_MUZZLEFLASH_SIMPLE_A3		= 5021,
	EVENT_CLIENTDLL_MUZZLEFLASH_SIMPLE_A4		= 5031,

	EVENT_CLIENTDLL_MUZZLEFLASH_2A_A1			= 6005,
	EVENT_CLIENTDLL_EJECTBULLET_A1				= 6010,
	EVENT_CLIENTDLL_EJECTBULLET_A2				= 6015,
	EVENT_CLIENTDLL_EJECTBULLET_A3				= 6025,
	EVENT_CLIENTDLL_EJECTBULLET_A4				= 6035,
	EVENT_CLIENTDLL_MUZZLEFLASH_1A_A1			= 6045,
	EVENT_CLIENTDLL_MUZZLEFLASH_1A_A2			= 6055,

	EVENT_CLIENTDLL_CREATE_PARTICLE_SYSTEM_A1	= 7005,
	EVENT_CLIENTDLL_CREATE_PARTICLE_SYSTEM_A2	= 7015,
	EVENT_CLIENTDLL_CREATE_PARTICLE_SYSTEM_A3	= 7025,
	EVENT_CLIENTDLL_CREATE_PARTICLE_SYSTEM_A4	= 7035,

	EVENT_CLIENTDLL_CREATE_PARTICLE_CLUSTER_A1	= 7045,
	EVENT_CLIENTDLL_CREATE_PARTICLE_CLUSTER_A2	= 7055,
	EVENT_CLIENTDLL_CREATE_PARTICLE_CLUSTER_A3	= 7065,
	EVENT_CLIENTDLL_CREATE_PARTICLE_CLUSTER_A4	= 7075,

	EVENT_CLIENTDLL_LADDER_STEP_SOUND			= 9001,
	EVENT_CLIENTDLL_NPC_STEP_SOUND				= 9002,

	EVENT_CLIENTDLL_VAPORTRAIL_SMOKE			= 10001,
	EVENT_CLIENTDLL_VAPORTRAIL_GLOW				= 10002,
};

#endif ANIMEVENT_H